Added a TimeOut Constructor Parameter
sendgrid/csharp-http-client pull request #10
Opened 2016-07-11 19:39 UTC by PandaBoy00

Added a TimeOut Parameter with a default of 10 seconds from a TimeSpan Object if the parameter was not supplied during the constructor.

2016-09-14 20:20 UTC, thinkingserious commented
Hi @PandaBoy00,

This one finally bubbled to the top of my queue. Could you please fix the conflicts so I can merge it? Thanks!

2016-09-15 12:44 UTC, PandaBoy00 commented
Hi Elmer,


Sure no problem.  But what was the conflict?  I was able to compile fine on my end.


Kengie


________________________________
From: Elmer Thomas <notifications@github.com>
Sent: Wednesday, September 14, 2016 4:20 PM
To: sendgrid/csharp-http-client
Cc: PandaBoy00; Mention
Subject: Re: [sendgrid/csharp-http-client] Added a TimeOut Constructor Parameter (#10)


Hi @PandaBoy00<https://github.com/PandaBoy00>,

This one finally bubbled to the top of my queue. Could you please fix the conflicts so I can merge it? Thanks!

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/sendgrid/csharp-http-client/pull/10#issuecomment-247140809>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ATQItvznebS8zFPfZy9JS5nuY7QM8iNHks5qqFcbgaJpZM4JJtPz>.

2016-09-15 17:31 UTC, thinkingserious commented
Hello @PandaBoy00,

After I do:

```bash
git checkout -b PandaBoy00-http-timeout-param master
git pull https://github.com/PandaBoy00/csharp-http-client.git http-timeout-param
```

I get a conflict in `Client.cs`, specifically:

```csharp
<<<<<<< HEAD
        public WebProxy WebProxy;
=======
        public TimeSpan Timeout;
>>>>>>> a01c011e11a9159b01b7e9147adb4f612defe718
```

2016-09-16 16:03 UTC, PandaBoy00 commented
Hi Elmer,


I have just resolved the conflict.  Can you please try again?  Thanks.


[cid:643c4b2b-b47b-4c8a-a7fd-4e5c54276d98]


Kengie


________________________________
From: Elmer Thomas <notifications@github.com>
Sent: Thursday, September 15, 2016 1:31 PM
To: sendgrid/csharp-http-client
Cc: PandaBoy00; Mention
Subject: Re: [sendgrid/csharp-http-client] Added a TimeOut Constructor Parameter (#10)


Hello @PandaBoy00<https://github.com/PandaBoy00>,

After I do:

git checkout -b PandaBoy00-http-timeout-param master
git pull https://github.com/PandaBoy00/csharp-http-client.git http-timeout-param

I get a conflict in Client.cs, specifically:

<<<<<<< HEAD
        public WebProxy WebProxy;
=======
        public TimeSpan Timeout;
>>>>>>> a01c011e11a9159b01b7e9147adb4f612defe718

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/sendgrid/csharp-http-client/pull/10#issuecomment-247395957>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ATQItt_ni0-fcJ5KMQLGo2fg8Mhd3TOCks5qqYEBgaJpZM4JJtPz>.

2016-09-21 19:47 UTC, thinkingserious commented
Hi @PandaBoy00,

It does not look like you have pushed your changes yet. Could you please try it again? Thanks!

2016-09-22 13:43 UTC, PandaBoy00 commented
Hi Elmer,


Sorry about this.  I push it to the branch http-timeout-param instead of the master branch on my fork.


It is now pushed to the master branch of my fork.  Sorry but I am not too familiar with command line git.  It should be all set now.


Regards,

Kengie


________________________________
From: Elmer Thomas <notifications@github.com>
Sent: Wednesday, September 21, 2016 3:47 PM
To: sendgrid/csharp-http-client
Cc: PandaBoy00; Mention
Subject: Re: [sendgrid/csharp-http-client] Added a TimeOut Constructor Parameter (#10)


Hi @PandaBoy00<https://github.com/PandaBoy00>,

It does not look like you have pushed your changes yet. Could you please try it again? Thanks!

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/sendgrid/csharp-http-client/pull/10#issuecomment-248722246>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ATQItpjGUtpjdEuQYH18R4OqQ2ABxF3eks5qsYnYgaJpZM4JJtPz>.

2016-09-26 20:54 UTC, thinkingserious commented
Thanks for making the update.

Unfortunately, we have a new set of conflicts:

```bash
CONFLICT (add/add): Merge conflict in README.md
Auto-merging LICENSE.txt
CONFLICT (add/add): Merge conflict in LICENSE.txt
Auto-merging CONTRIBUTING.md
CONFLICT (add/add): Merge conflict in CONTRIBUTING.md
Auto-merging CHANGELOG.md
CONFLICT (add/add): Merge conflict in CHANGELOG.md
Auto-merging .travis.yml
CONFLICT (add/add): Merge conflict in .travis.yml
Auto-merging .gitignore
CONFLICT (add/add): Merge conflict in .gitignore
Auto-merging .github/ISSUE_TEMPLATE
CONFLICT (add/add): Merge conflict in .github/ISSUE_TEMPLATE
```

Could you please take a look? Thanks!

2016-09-27 16:26 UTC, PandaBoy00 commented
I have just rechecked in the conflicted files.  Please try again.  Screen Capture for your reference.


________________________________
From: Elmer Thomas <notifications@github.com>
Sent: Monday, September 26, 2016 4:54 PM
To: sendgrid/csharp-http-client
Cc: PandaBoy00; Mention
Subject: Re: [sendgrid/csharp-http-client] Added a TimeOut Constructor Parameter (#10)


Thanks for making the update.

Unfortunately, we have a new set of conflicts:

CONFLICT (add/add): Merge conflict in README.md
Auto-merging LICENSE.txt
CONFLICT (add/add): Merge conflict in LICENSE.txt
Auto-merging CONTRIBUTING.md
CONFLICT (add/add): Merge conflict in CONTRIBUTING.md
Auto-merging CHANGELOG.md
CONFLICT (add/add): Merge conflict in CHANGELOG.md
Auto-merging .travis.yml
CONFLICT (add/add): Merge conflict in .travis.yml
Auto-merging .gitignore
CONFLICT (add/add): Merge conflict in .gitignore
Auto-merging .github/ISSUE_TEMPLATE
CONFLICT (add/add): Merge conflict in .github/ISSUE_TEMPLATE

Could you please take a look? Thanks!

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/sendgrid/csharp-http-client/pull/10#issuecomment-249694619>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ATQItr2CR4cVPUMk-qZen5FwDrLp_gdOks5quDEOgaJpZM4JJtPz>.

2016-09-27 17:41 UTC, thinkingserious commented
@PandaBoy00,

Can you please push your changes? Thanks!

2016-09-27 18:46 UTC, PandaBoy00 commented
Hi there,


Sorry for the troubles.


I have already push my changes to the repo https://github.com/PandaBoy00/csharp-http-client.git.


and everything is already updated.


Please see screen shot for reference.  Is there anything else I'm not doing correctly?  Thanks.

[https://avatars1.githubusercontent.com/u/20187318?v=3&s=400]<https://github.com/PandaBoy00/csharp-http-client.git>

PandaBoy00/csharp-http-client<https://github.com/PandaBoy00/csharp-http-client.git>
github.com
csharp-http-client - HTTP client for RESTful APIs, simplified for C#




________________________________
From: Elmer Thomas <notifications@github.com>
Sent: Tuesday, September 27, 2016 1:41 PM
To: sendgrid/csharp-http-client
Cc: PandaBoy00; Mention
Subject: Re: [sendgrid/csharp-http-client] Added a TimeOut Constructor Parameter (#10)


@PandaBoy00<https://github.com/PandaBoy00>,

Can you please push your changes? Thanks!

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/sendgrid/csharp-http-client/pull/10#issuecomment-249940596>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ATQItnm9U0Xt8x1lNwwp7Hk-O3U_pZlKks5quVVRgaJpZM4JJtPz>.

2016-09-27 20:23 UTC, thinkingserious requested changes
Please see my comment.

With regards to the merge, I'm not sure what is going on. Maybe it's easier to just create a new fork and just replace this file.

2016-09-27 20:23 UTC, thinkingserious commented on CSharpHTTPClient/Client.cs
> +            Timeout = (timeOut != null) ? (TimeSpan)timeOut : TimeSpan.FromSeconds(10);
Can we make the value passed to TimeSpan.FromSeconds configurable?

2016-09-28 12:59 UTC, PandaBoy00 commented
Not really sure what you mean from configurable?  Do you mean to get the value from AppSetting?


Currently it is getting a values from the parameter is set, otherwise it will default to 10 seconds.


________________________________
From: Elmer Thomas <notifications@github.com>
Sent: Tuesday, September 27, 2016 4:23 PM
To: sendgrid/csharp-http-client
Cc: PandaBoy00; Mention
Subject: Re: [sendgrid/csharp-http-client] Added a TimeOut Constructor Parameter (#10)


@thinkingserious requested changes on this pull request.

Please see my comment.

With regards to the merge, I'm not sure what is going on. Maybe it's easier to just create a new fork and just replace this file.

________________________________

In CSharpHTTPClient/Client.cs<https://github.com/sendgrid/csharp-http-client/pull/10#pullrequestreview-1816871>:

> @@ -90,6 +92,7 @@ public Client(string host, Dictionary<string,string> requestHeaders = null, stri
             }
             Version = (version != null) ? version : null;
             UrlPath = (urlPath != null) ? urlPath : null;
+            Timeout = (timeOut != null) ? (TimeSpan)timeOut : TimeSpan.FromSeconds(10);


Can we make the value passed to TimeSpan.FromSeconds configurable?

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/sendgrid/csharp-http-client/pull/10#pullrequestreview-1816871>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ATQIturJwprO-NA7XhWiUdCsIWcjiH8Oks5quXs7gaJpZM4JJtPz>.

2016-09-28 16:20 UTC, thinkingserious commented
@PandaBoy00,

I'm suggesting that default value be configurable.

2016-10-05 13:18 UTC, PandaBoy00 commented
Hi there,


I have made the modification based on your suggested and also have check it in.


________________________________
From: Elmer Thomas <notifications@github.com>
Sent: Wednesday, September 28, 2016 12:20 PM
To: sendgrid/csharp-http-client
Cc: PandaBoy00; Mention
Subject: Re: [sendgrid/csharp-http-client] Added a TimeOut Constructor Parameter (#10)


@PandaBoy00<https://github.com/PandaBoy00>,

I'm suggesting that default value be configurable.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/sendgrid/csharp-http-client/pull/10#issuecomment-250218443>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ATQItv2azMinnn-2-PM6g3aUVOyfvnnGks5qupPjgaJpZM4JJtPz>.

2016-10-05 17:06 UTC, thinkingserious approved these changes

2016-10-05 17:07 UTC, thinkingserious commented
@PandaBoy00,

I see the changes on your branch, but they have not been pushed here. Can you please merge them back here? Thanks!

2016-10-05 18:00 UTC, PandaBoy00 commented
I have merge both of my branches master and http-timeout-param.  They are both up to date.


Thanks.

________________________________
From: Elmer Thomas <notifications@github.com>
Sent: Wednesday, October 5, 2016 1:07 PM
To: sendgrid/csharp-http-client
Cc: PandaBoy00; Mention
Subject: Re: [sendgrid/csharp-http-client] Added a TimeOut Constructor Parameter (#10)


@PandaBoy00<https://github.com/PandaBoy00>,

I see the changes on your branch, but they have not been pushed here. Can you please merge them back here? Thanks!

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/sendgrid/csharp-http-client/pull/10#issuecomment-251736567>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ATQItljv2QaMzJl9ViYT3F5qQMPwDiDgks5qw9lVgaJpZM4JJtPz>.

2016-10-05 18:37 UTC, thinkingserious requested changes

2016-10-05 18:37 UTC, thinkingserious commented on .travis.yml
> +
It looks like this edit is causing the tests to fail. Could you please revert this file?

2016-10-06 12:55 UTC, PandaBoy00 commented
I have revert the file back to the original from your fork.  You can try again now.


________________________________
From: Elmer Thomas <notifications@github.com>
Sent: Wednesday, October 5, 2016 2:37 PM
To: sendgrid/csharp-http-client
Cc: PandaBoy00; Mention
Subject: Re: [sendgrid/csharp-http-client] Added a TimeOut Constructor Parameter (#10)


@thinkingserious requested changes on this pull request.

________________________________

In .travis.yml<https://github.com/sendgrid/csharp-http-client/pull/10#pullrequestreview-2976120>:

> @@ -18,3 +18,5 @@ notifications:
       Build %{build_number}</a> on branch <i>%{branch}</i> by %{author}: <strong>%{message}</strong>
       <a href="https://github.com/%{repository}/commits/%{commit}">View on GitHub</a>'
     format: html
+


It looks like this edit is causing the tests to fail. Could you please revert this file?

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/sendgrid/csharp-http-client/pull/10#pullrequestreview-2976120>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ATQItsaeh9DhF-V8LM4O60B2qcGtwW_-ks5qw-5wgaJpZM4JJtPz>.

2016-10-06 13:09 UTC, thinkingserious approved these changes

2016-10-06 23:26 UTC, thinkingserious requested changes

2016-10-06 23:26 UTC, thinkingserious commented on CSharpHTTPClient/Client.cs
> +<<<<<<< HEAD
These lines are the issue.

2016-10-06 23:26 UTC, thinkingserious commented on CSharpHTTPClient/Client.cs
> +<<<<<<< HEAD
Here is another case.

2016-10-11 19:32 UTC, thinkingserious approved these changes

2016-10-11 19:32 UTC, thinkingserious commented
@PandaBoy00,

It might be easier to just start over with a new PR.

2016-10-12 16:17 UTC, PandaBoy00 commented
Sure, I'll do another PR later.  A bit busy recently.


________________________________
From: Elmer Thomas <notifications@github.com>
Sent: Tuesday, October 11, 2016 3:32 PM
To: sendgrid/csharp-http-client
Cc: PandaBoy00; Mention
Subject: Re: [sendgrid/csharp-http-client] Added a TimeOut Constructor Parameter (#10)


@PandaBoy00<https://github.com/PandaBoy00>,

It might be easier to just start over with a new PR.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/sendgrid/csharp-http-client/pull/10#issuecomment-253020516>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ATQItvKTpbDj-8gbLrLg2rIr6lqIYk2Oks5qy-RqgaJpZM4JJtPz>.

2016-10-12 17:43 UTC, thinkingserious commented
Thanks @PandaBoy00!

2016-10-27 20:07 UTC, thinkingserious commented
Hi @PandaBoy00,

Just checking in with you :)

2016-10-28 12:05 UTC, PandaBoy00 commented
Hi Elmer,


Sorry just kinda busy @ work.  I will do another PR asap.


________________________________
From: Elmer Thomas <notifications@github.com>
Sent: Thursday, October 27, 2016 4:07 PM
To: sendgrid/csharp-http-client
Cc: PandaBoy00; Mention
Subject: Re: [sendgrid/csharp-http-client] Added a TimeOut Constructor Parameter (#10)


Hi @PandaBoy00<https://github.com/PandaBoy00>,

Just checking in with you :)

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/sendgrid/csharp-http-client/pull/10#issuecomment-256754344>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ATQItocm6HPHllHWfdVWc_DxVu-vG6Jiks5q4QR7gaJpZM4JJtPz>.

2017-03-01 19:10 UTC, thinkingserious commented
Hi @PandaBoy00,

Were you still considering making a new PR?

2017-03-01 19:43 UTC, PandaBoy00 commented
Hi Elmer,


Yes but I was tied up with work and vacation.  I will do one next week.


________________________________
From: Elmer Thomas <notifications@github.com>
Sent: Wednesday, March 1, 2017 2:10 PM
To: sendgrid/csharp-http-client
Cc: PandaBoy00; Mention
Subject: Re: [sendgrid/csharp-http-client] Added a TimeOut Constructor Parameter (#10)


Hi @PandaBoy00<https://github.com/PandaBoy00>,

Were you still considering making a new PR?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/sendgrid/csharp-http-client/pull/10#issuecomment-283438420>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ATQItpaCfLZW5vrtDruHKTE0AdggB7pyks5rhcLBgaJpZM4JJtPz>.

2017-03-01 19:55 UTC, thinkingserious commented
@PandaBoy00,

No worries, thanks for the update and congrats on the vacation!

2017-03-16 17:05 UTC, thinkingserious commented
Hi @PandaBoy00,

Just checking in, I hope all is well.

2017-03-23 12:02 UTC, PandaBoy00 commented
Hi Elmer,


Yeah, I will do another PR today.


________________________________
From: Elmer Thomas <notifications@github.com>
Sent: Thursday, March 16, 2017 1:05 PM
To: sendgrid/csharp-http-client
Cc: PandaBoy00; Mention
Subject: Re: [sendgrid/csharp-http-client] Added a TimeOut Constructor Parameter (#10)


Hi @PandaBoy00<https://github.com/PandaBoy00>,

Just checking in, I hope all is well.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/sendgrid/csharp-http-client/pull/10#issuecomment-287124985>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ATQItlRX2uIrai8CV17YeoFxjWdkbmjeks5rmWvzgaJpZM4JJtPz>.

2017-04-11 17:59 UTC, PandaBoy00 commented
Moved over to new PR

2017-04-11 17:59 UTC, closed without merging