Added cancellation of requests using CancellationToken
sendgrid/csharp-http-client pull request #22
Opened 2017-01-10 19:57 UTC by aKzenT

Please see related issue #21

2017-01-10 19:57 UTC, thinkingserious commented
Hello @aKzenT,<br /><br/>Thank you for the PR!<br />                                              <br />We will be reviewing this PR soon, in the mean                                              time, if you have not, please be sure to                                              <a href="https://github.com/sendgrid/csharp-http-client/blob/master/CONTRIBUTING.md#cla">                                             sign our CLA</a> so that we can merge your changes. Thanks again!                                             <br /><br />Team DX

2017-01-26 00:01 UTC, thinkingserious commented
Hello @aKzenT,

Do you mind sending over a [signed CLA](https://github.com/sendgrid/csharp-http-client/blob/master/CONTRIBUTING.md#cla) so I can review and merge?

Thanks!

2017-01-26 08:09 UTC, aKzenT commented
Already did that a few weeks ago.

Am 26.01.2017 01:01 schrieb "Elmer Thomas" <notifications@github.com>:

> Hello @aKzenT <https://github.com/aKzenT>,
>
> Do you mind sending over a signed CLA
> <https://github.com/sendgrid/csharp-http-client/blob/master/CONTRIBUTING.md#cla>
> so I can review and merge?
>
> Thanks!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/sendgrid/csharp-http-client/pull/22#issuecomment-275271486>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ACeCAKJudI8O-ivJOQWPwrxWBzmu-kVyks5rV-JLgaJpZM4Lf1Dk>
> .
>

2017-01-26 18:24 UTC, thinkingserious commented
Thanks @aKzenT,

I do not see it however, can you please let me know from what email you sent it from? (Please reply to dx@sendgrid.com)

2017-02-20 21:10 UTC, thinkingserious commented
Hi @aKzenT,

I have not received the CLA or follow up email from you. Could you please resend or let me know what email address you used to send it? Thanks!

2017-02-20 21:26 UTC, aKzenT commented
I send it again, now from another email address and to your own email address just in case.

2017-02-20 21:45 UTC, thinkingserious commented
@aKzenT,

We received it, thanks!

As for v9, it's available now:
https://github.com/sendgrid/sendgrid-csharp
https://www.nuget.org/packages/SendGrid

With Best Regards,

Elmer

2017-03-10 19:50 UTC, thinkingserious requested changes

2017-03-10 19:50 UTC, thinkingserious commented on CSharpHTTPClient/Client.cs
> +                result = RequestAsync(binder.Name.ToUpper(), cancellationToken, requestBody: requestBody, queryParams: queryParams).ConfigureAwait(false);
Please move the `cancellationToken` parameter to the end for consistency with our v9 SDK.

2017-03-10 19:50 UTC, thinkingserious commented on CSharpHTTPClient/Client.cs
> +        private async Task<Response> RequestAsync(string method, CancellationToken cancellationToken, string requestBody = null, string queryParams = null)
Please move the `cancellationToken` parameter to the end for consistency with our v9 SDK.

2017-04-13 17:46 UTC, thinkingserious commented
Hi @aKzenT,

To merge this, could you please:

1. Resolve the conflicts
2. Give the cancellation token a default value so we don't have to make a breaking change

Thanks!

2017-04-15 20:45 UTC, SendGridDX commented
[![CLA assistant check](https://cla.sendgrid.com/pull/badge/not_signed)](https://cla.sendgrid.com/sendgrid/csharp-http-client?pullRequest=22) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/csharp-http-client?pullRequest=22) before we can accept your contribution.<br/><hr/>**Thomas Krause** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/csharp-http-client?pullRequest=22) it.</sub>

2017-04-17 16:29 UTC, thinkingserious approved these changes

2017-04-17 19:46 UTC, merged

2017-04-17 19:46 UTC, thinkingserious commented
Hello @aKzenT,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

2017-04-17 21:35 UTC, aKzenT commented
Done, Thanks!